/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tomato.crush;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author user
 */
public class Scoreboard extends javax.swing.JFrame {

    private final String username;

    /**
     * Creates new form Scoreboard
     */
    public Scoreboard(String username) {
        initComponents();
        this.username = username;
        fetchAndUpdateLabels(username);
    }

    private void fetchAndUpdateLabels(String username) {
        try (Connection connection = DatabaseConnector.connect(); PreparedStatement preparedStatement = connection.prepareStatement(
                "SELECT pp.`level_id`, pp.`correct_answers`, pp.`time_to_complete` "
                + "FROM `playerprogress` pp "
                + "JOIN `players` p ON pp.`player_id` = p.`id` "
                + "WHERE p.`user_name` = ? "
                + "ORDER BY pp.`level_id` DESC "
                + "LIMIT 1")) {

            preparedStatement.setString(1, username);

            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    int maxLevel = resultSet.getInt("level_id");
                    int maxCorrectAnswers = resultSet.getInt("correct_answers" );
                    String maxTime = resultSet.getString("time_to_complete");

                    // Update labels
                    lblLevel.setText(String.valueOf(maxLevel));
                    lblScore.setText(String.valueOf(maxCorrectAnswers));
                    lblTime.setText(maxTime);
                    lblDisplayName.setText(username);
                } else {
                    // If there is no row for the current user, assign default values
                    lblLevel.setText("0");
                    lblScore.setText("0");
                    lblTime.setText("00:00");
                    lblDisplayName.setText(username);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLevelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTimeTitle = new javax.swing.JLabel();
        lblDisplayName = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblScoreTitle2 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLevelTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 19)); // NOI18N
        lblLevelTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLevelTitle.setText("Current Level:");
        lblLevelTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLevelTitleMouseClicked(evt);
            }
        });
        getContentPane().add(lblLevelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/New folder/button6.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        lblTimeTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 19)); // NOI18N
        lblTimeTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeTitle.setText("Best Time:");
        lblTimeTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTimeTitleMouseClicked(evt);
            }
        });
        getContentPane().add(lblTimeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 180, 40));

        lblDisplayName.setFont(new java.awt.Font("Comic Sans MS", 1, 19)); // NOI18N
        lblDisplayName.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplayName.setText("Name:");
        lblDisplayName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDisplayNameMouseClicked(evt);
            }
        });
        getContentPane().add(lblDisplayName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, 40));

        lblLevel.setFont(new java.awt.Font("Comic Sans MS", 1, 19)); // NOI18N
        lblLevel.setForeground(new java.awt.Color(255, 255, 0));
        lblLevel.setText("05");
        lblLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLevelMouseClicked(evt);
            }
        });
        getContentPane().add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 180, 40));

        lblScoreTitle2.setFont(new java.awt.Font("Comic Sans MS", 1, 19)); // NOI18N
        lblScoreTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblScoreTitle2.setText("Your Score :");
        lblScoreTitle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblScoreTitle2MouseClicked(evt);
            }
        });
        getContentPane().add(lblScoreTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 180, 40));

        lblTime.setFont(new java.awt.Font("Comic Sans MS", 1, 19)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 0));
        lblTime.setText("01:35");
        lblTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTimeMouseClicked(evt);
            }
        });
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 180, 40));

        lblScore.setFont(new java.awt.Font("Comic Sans MS", 1, 19)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 0));
        lblScore.setText("12345");
        lblScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblScoreMouseClicked(evt);
            }
        });
        getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 180, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/New folder/Score board.jpg"))); // NOI18N
        lblBackground.setText(" ");
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLevelTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLevelTitleMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblLevelTitleMouseClicked

    private void lblTimeTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimeTitleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTimeTitleMouseClicked

    private void lblDisplayNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDisplayNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDisplayNameMouseClicked

    private void lblLevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLevelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLevelMouseClicked

    private void lblScoreTitle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScoreTitle2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblScoreTitle2MouseClicked

    private void lblTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTimeMouseClicked

    private void lblScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScoreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblScoreMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         Menu form = new Menu(username);
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Scoreboard("player").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDisplayName;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLevelTitle;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoreTitle2;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeTitle;
    // End of variables declaration//GEN-END:variables
}
